# FONT SETTINGS
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        8.0
disable_ligatures cursor

# PERFORMANCE AND RENDERING
repaint_delay    8
input_delay      2
sync_to_monitor  yes
scrollback_lines 10000

# HYPRLAND AND WINDOW STYLE
window_padding_width 8
hide_window_decorations yes
placement_strategy center
inactive_text_alpha 0.5
background_opacity 1.0

# COLOUR SCHEME
foreground #c0c0c0
background #0c0c0c
cursor     #22dd22
selection_foreground #000000
selection_background #666666
url_style  double

# CURSOR BEHAVIOUR
cursor_shape block
cursor_blink_interval 0.5

# INTEGRATION AND REMOTE CONTROL
#shell bash
update_check_interval 0
allow_remote_control yes
listen_on unix:@kitty

# KEYBOARD MAPPINGS
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# window management
map ctrl+shift+w close_window

# terminal signals
map ctrl+c send_text all \x03
