# WINDOW
window_padding_width 8
hide_window_decorations yes
background_opacity 1.0

# SCROLLBACK
scrollback_lines 10000
mouse_hide_wait -1

# FONT
font_size 7.5
font_family JetBrainsMono Nerd Font
bold_font JetBrainsMono Nerd Font Bold
italic_font JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic

# -COLOURS
foreground #cecdc3
background #000000
cursor_text_color #100f0f

color0  #100f0f
color1  #af3029
color2  #66800b
color3  #ad8301
color4  #205ea6
color5  #5e409d
color6  #24837b
color7  #cecdc3

color8  #282726
color9  #d14d41
color10 #879a39
color11 #d0a215
color12 #4385be
color13 #8b7ec8
color14 #3aa99f
color15 #e6e4d9

# SHELL
#shell /home/dil/.local/bin/tmux-wrapper
