# THE NOIR THEME

[main]
# fuzzel requires wrapper scripts for dynamic per-mode prompts
prompt="APP: "
font=JetBrainsMono Nerd Font:size=8,Noto Color Emoji:size=8
# character width dictates the horizontal size
width=50
lines=8
icons-enabled=yes
terminal=footclient
# disable the generic exit button to maintain the sharp aesthetic
exit-on-keyboard-focus-loss=yes

[colors]
# flexoki ink translations
background=100f0fff
text=cecdc3ff
match=8b7ec8ff
selection=282726ff
selection-text=cecdc3ff
selection-match=8b7ec8ff
border=343331ff

[border]
width=1
radius=0
