# CORE ENVIRONMENT
set -g prefix C-b
bind C-b send-prefix

set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on

set -g default-terminal "tmux-256color"

set -g mouse on
set -g mode-keys vi

# STATUS BAR
set -g status-position top
set -g status-justify right

set -g status-style bg="#100f0f",fg="#cecdc3"

set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-current-style bg="#282726",fg="#8b7ec8",bold

set -g status-left " [#S] "
set -g status-left-length 40

set -g status-right ""
set -g status-right-length 80
