# CORE ENVIRONMENT
set -g prefix C-b
bind C-b send-prefix
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",alacritty:Tc"
set -g mouse on
set-window-option -g mode-keys vi

# STATUS BAR
set-option -g status-position top
set-option -g status-justify right
set -g status-style bg="#100f0f",fg="#cecdc3"
set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "
set -g window-status-current-style bg="#282726",fg="#8b7ec8",bold
set -g status-left " [#S] "
set -g status-left-length 40
set -g status-right "#(/home/dil/go/bin/gitmux '#{pane_current_path}') #[fg=#8b7ec8,bold]#(echo #{pane_current_path} | sed 's|^$HOME|~|') "
set -g status-right-length 80

# PLUGIN ROUTING
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# STATE AUTOMATION
set -g @continuum-restore 'on'
set -g @continuum-save-interval '15'

# EXECUTION
run '~/.tmux/plugins/tpm/tpm'
