# FOOT TERMINAL CONFIG
# foot 1.27.0

[main]
term=foot
font=JetBrainsMono Nerd Font:size=9
pad=8x8
dpi-aware=no

[scrollback]
lines=10000
multiplier=3

[cursor]
style=block
blink=no

[mouse]
hide-when-typing=yes

# FLEXOKI INK DARK
[colors-dark]
background=100f0f
foreground=cecdc3
# cursor: foreground(text) background(block) — two values, space-separated
cursor=100f0f cecdc3

regular0=100f0f
regular1=af3029
regular2=66800b
regular3=ad8301
regular4=205ea6
regular5=5e409d
regular6=24837b
regular7=cecdc3

bright0=282726
bright1=d14d41
bright2=879a39
bright3=d0a215
bright4=4385be
bright5=8b7ec8
bright6=3aa99f
bright7=e6e4d9
