# CONNECTION
host = "127.0.0.1"
port = 6600

# UI LAYOUT
show_status_bar = true
show_playback_info = true
show_browser = true
show_playlist = true

# Keep interface tight and column-like
layout = "split"

# BEHAVIOUR
scrolloff = 5
seek_step = 5

# VISUAL SIMPLICITY
show_help = false
wrap_navigation = true
