alias pm='sudo pacman'
alias pr='paru'

alias ls='ls --color=always'
alias lz='eza --group-directories-first'
alias l='eza -l --group-directories-first --git'
alias li='eza -laai --group-directories-first --git'
alias la='eza -la --group-directories-first --git'
alias lt='eza -l --tree --group-directories-first --git'
alias lta='eza -la --tree --group-directories-first --git'
alias lt2='eza --tree --level=2'
alias lt3='eza --tree --level=3'
alias cat='bat --paging=never'
alias bap='bat --paging=always'
alias b='bat'

alias cp='cp -iv'
alias mv='mv -iv'
alias rm='rm -Iv'
alias rmr='rm -Irv'
alias rmf='rm -frv'
alias mkdir='mkdir -pv'

alias ,='nvim'
alias ,,='sudo nvim'

alias grep='grep --color=auto'
alias diff='diff --color=auto'
alias ip='ip --color=auto'
alias df='df -h'
alias du='du -h'
alias free='free -h'
alias chmod='chmod -v'
alias suchmod='sudo chmod -v'
alias cls='clear'
alias path='echo $PATH | tr ":" "\n"'
alias reload='exec bash'

alias -g L='| less'
alias -g G='| grep -i'
alias -g WC='| wc -l'
alias -g NUL='>/dev/null 2>&1'
alias -g E='2>&1'
alias -g COPY='| wl-copy'
alias -g ANSICOPY='| ansifilter | wl-copy'

alias fullcharge='sudo tlp fullcharge'
alias paste='wl-paste'
alias ic='incus'

alias py='python3'
alias ipy='ipython'

alias zt='zathura'

alias sys='systemctl'
alias susys='sudo systemctl'
