alias hl='hledger'
alias hlb='hledger bal'
alias hlbe='hledger bal Expenses'
alias hlbi='hledger bal Income'
alias hlr='hledger reg'
alias hlis='hledger incomestatement'
alias hlu='hledger-ui'
alias hlw='hledger-web'
