# --- WINDOW RULES ---

windowrulev2 = float, class:^(pavucontrol)$
windowrulev2 = float, class:^(blueman-manager)$
windowrulev2 = float, class:^(nm-connection-editor)$

windowrulev2 = float, class:(clipyazi)
windowrulev2 = size 60% 60%, class:(clipyazi)
windowrulev2 = center, class:(clipyazi)

# Prevent apps from blocking screen locking
windowrulev2 = suppressevent maximize, class:.*

# --- LIBREWOLF PIP (Engineered) ---
windowrulev2 = float, class:^(librewolf)$, title:^(Picture-in-Picture)$
windowrulev2 = pin, class:^(librewolf)$, title:^(Picture-in-Picture)$
windowrulev2 = size 30% 30%, class:^(librewolf)$, title:^(Picture-in-Picture)$
windowrulev2 = move 100%-w-20 100%-h-20, class:^(librewolf)$, title:^(Picture-in-Picture)$

# --- MINI SHELL ENV ---
#windowrulev2 = workspace special:magic, class:^(miniterm)$
#windowrulev2 = float, class:^(miniterm)$
#windowrulev2 = size 800 500, class:^(miniterm)$
#windowrulev2 = center, class:^(miniterm)$
#windowrulev2 = dimaround, class:^(miniterm)$

# Force the miniterm to be exactly 1 line high
windowrulev2 = size 800 40, class:^(miniterm)$
windowrulev2 = center, class:^(miniterm)$
