# FILES
music_directory    "~/Music"
playlist_directory "~/.config/mpd/playlists"
db_file            "~/.config/mpd/database"
log_file           "syslog"
pid_file           "/tmp/mpd.pid"
state_file         "~/.config/mpd/state"

# NETWORK
bind_to_address    "127.0.0.1"
port               "6600"

# AUDIO OUTPUT (PipeWire/Pulse)
audio_output {
    type "pulse"
    name "pulse audio"
}

# VISUALISER FEED
audio_output {
    type "fifo"
    name "visualiser"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
    enabled "yes"
}

# TWEAKS
auto_update         "yes"
restore_paused      "yes"
