default-remote: local
remotes:
  images:
    protocol: simplestreams
    public: true
    addr: https://images.linuxcontainers.org
  local:
    protocol: incus
    public: false
    addr: unix://
aliases:
  aka: alias
  apus: pause --all
  astp: stop --all
  astr: start --all
  bash: exec @ARGS@ -- bash
  c: config
  del: delete
  df: exec @ARG1@ -- df -h
  e: exec
  i: info
  img: image
  l: list --columns=ns4 --format=csv
  logs: exec @ARG1@ -- journalctl -u @ARG2@
  ps: exec @ARG1@ -- ps aux
  pus: pause
  reboot: exec @ARG1@ -- reboot
  shell: exec @ARG1@ -- su -l
  stp: stop
  str: start
  top: exec @ARG1@ -- top
  user: exec @ARG1@ -- sudo -iu @ARG2@
  zsh: exec @ARGS@ -- zsh
defaults:
  list_format: "compact,noheader"
  console_type: ""
  console_spice_command: ""
  no_color: false
