# Prefix adjustment
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config with 'r' (Updated to point to the new location)
bind r source-file ~/.config/tmux/tmux.conf \; display "Config Reloaded!"

# Split in CWD
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Vim Pane selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
