# --- GENERAL ---
general {
    gaps_in = 4
    gaps_out = 8
    border_size = 1

    col.active_border = $foreground
    col.inactive_border = $background

    layout = dwindle
}

# --- DECORATION ---
decoration {
    rounding = 0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

# --- ANIMATIONS ---
animations {
    enabled = yes

    bezier = sharp, 0.25, 1, 0.5, 1

    animation = windows, 1, 4, sharp, slide
    animation = windowsOut, 1, 4, sharp, slide
    animation = border, 1, 10, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, sharp, slide
}

# --- LAYOUTS ---
dwindle {
    pseudotile = yes
    preserve_split = yes
}

master {
    new_status = master
}
