# GENERAL
general {
    gaps_in = 2
    gaps_out = 2
    border_size = 1

    col.active_border = $foreground
    col.inactive_border = $background

    layout = master
}

# DECORATION
decoration {
    rounding = 0

    blur {
        enabled = false
    }

    shadow {
        enabled = false
    }
}

# ANIMATIONS
animations {
    enabled = yes
    bezier = sharp, 0.25, 1, 0.5, 1
    animation = windows, 1, 4, sharp, slide
    animation = windowsOut, 1, 4, sharp, slide
    animation = border, 1, 10, default
    animation = fade, 1, 5, default
    animation = workspaces, 1, 5, sharp, slide
}

# LAYOUT ENGINES
master {
    mfact = 0.50
    orientation = center
    new_on_top = true
    new_status = master
}

dwindle {
    pseudotile = yes
    preserve_split = yes
}

# WORKSPACES

# odds: master layout
workspace = 1, layout:master
workspace = 3, layout:master
workspace = 5, layout:master
workspace = 7, layout:master
workspace = 9, layout:master

# evens: dwindle layout
workspace = 2, layout:dwindle
workspace = 4, layout:dwindle
workspace = 6, layout:dwindle
workspace = 8, layout:dwindle
workspace = 10, layout:dwindle

# MISCELLANEOUS
misc {
    force_default_wallpaper = 0 
    disable_hyprland_logo = true
}
