# --- ENVIRONMENT VARIABLES ---
env = GDK_BACKEND,wayland,x11,*
env = QT_QPA_PLATFORM,wayland;xcb
env = SDL_VIDEODRIVER,wayland
env = CLUTTER_BACKEND,wayland

env = XCURSOR_SIZE,24
env = QT_QPA_PLATFORMTHEME,qt5ct
env = QT_STYLE_OVERRIDE,kvantum

env = SAL_USE_VCLPLUGIN,gtk3

env = GTK_THEME,Adwaita:dark

env = DESKTOP_SESSION,hyprland

# --- AUTOSTART ---
# Authentication / system agents
exec-once = /usr/lib/polkit-kde-authentication-agent-1

# Wallpaper
#exec-once = hyprpaper
exec-once = hyprpaper

# Idle & locking
exec-once = hypridle

# UI components
exec-once = waybar
exec-once = mako

# Clipboard management (textnotify-send "Success" "We are officially autostarting!" + images)
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DBUS_SESSION_BUS_ADDRESS
