# --- COLORS ---
$background = rgb(1a1a1a)
$foreground = rgb(b4befe)
$muted_accent = rgb(4a4a4a)

# --- APPLICATIONS ---
$mainMod = SUPER
$term_1 = kitty
$term_2 = foot
$launcher = rofi -show drun
$files = yazi
$browser_1 = zen-browser
$browser_2 = mullvad-browser
$notes = obsidian
$auth = enteauth
$photo = ente-desktop
$passwdm = bitwarden-desktop
$game_1 = dolphin-emu
$game_2 = azahar
