# COLOURS
$background = rgb(100f0f)
$foreground = rgb(343331)
$muted_accent = rgb(506507)

# APPLICATIONS
$mainMod = SUPER
$term = footclient
$launcher = rofi -show drun
$files = yazi
$browser_1 = zen-browser
$browser_2 = mullvad-browser
$notes = obsidian
$auth = enteauth
$photo = ente-desktop
$passwdm = bitwarden-desktop
$game_1 = dolphin-emu
$game_2 = azahar
