# --- COLORS ---
$background = rgb(1a1a1a)
$foreground = rgb(b4befe)
$muted_accent = rgb(4a4a4a)

# --- APPLICATIONS ---
$mainMod = SUPER
$term = kitty
$launcher = rofi -show drun
$files = yazi
$browser = floorp
$notes = obsidian
